// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5933.Sonny;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import org.usfirst.frc5933.Sonny.LidarLitePWM;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon ballReleaseLeft;
    public static DigitalInput ballReleaseLightSensor;
    public static LidarLitePWM ballReleaseGoogleyEyes;
	private static Thread lidarThread;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        ballReleaseLeft = new CANTalon(2);
        LiveWindow.addActuator("BallRelease", "Left", ballReleaseLeft);
        
        ballReleaseLightSensor = new DigitalInput(0);
        LiveWindow.addSensor("BallRelease", "LightSensor", ballReleaseLightSensor);
        
        ballReleaseGoogleyEyes = new LidarLitePWM(9, 8, 10, 100, true);
        
        lidarThread = new Thread(ballReleaseGoogleyEyes);
		lidarThread.start();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
